services:
  - type: web
    name: url-phishing-detector
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PIP_VERSION
        value: 24.0.0
